INSERT INTO EVENT values(1001, SYSDATE  , 'Event1', TRUE);
INSERT INTO EVENT values(1002, SYSDATE , 'Event2', TRUE);
INSERT INTO EVENT values(1003, SYSDATE , 'Event3', TRUE);
INSERT INTO EVENT values(1004, SYSDATE , 'Event4', TRUE);